### ISSUE TITLE
REQUEST: New Reviewer status for scottfrederick

### ISSUE THREAD

**Issue by scottfrederick** [spinnaker/community#10]
### Github Username

@scottfrederick

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @jammy-louie
- @claymccoy

### List of qualifications for this position

PRs
- https://github.com/spinnaker/clouddriver/pull/3638
- https://github.com/spinnaker/clouddriver/pull/3682
- https://github.com/spinnaker/clouddriver/pull/3683
- https://github.com/spinnaker/clouddriver/pull/3812 (in review)
- https://github.com/spinnaker/kork/pull/286

Design docs
- [Spinnaker External Configuration](https://docs.google.com/document/d/16EWk-ChZkae87hCSCFdl3ElepTLC-ac-4uv1tCyfZcc/edit#heading=h.p3ml0d5v2qon)
- [Spinnaker Config Secrets Using Config Server](https://docs.google.com/document/d/1Y7SIgobc8_CCFmFZLRUGl-76sfHWlprFYGy992S5U4A/edit#heading=h.sai17pl3aws8)

**Comment by ezimanyi** [comment]
+1
I would approve adding @scottfrederick as a reviewer based on the PRs to refactor account creation and enable Spring Cloud config, and based on participation to present this work to the Kubernetes SIG.

**Comment by ethanfrogers** [comment]
+2
@scottfrederick has been doing great work to enable dynamic accounts and has been a big help in porting that work to the Kubernetes provider.

**Comment by robzienert** [comment]
+1

**Comment by ajordens** [comment]
+1

**Comment by ajordens** [comment]
Added to https://github.com/spinnaker/spinnaker/blob/master/reviewers.md and sent invite to join the `Reviewers` GitHub team.
