### ISSUE TITLE
PROPOSAL: New Cloud Provider for AlibabaCloud(alicloud)

### ISSUE THREAD

**Issue by xiaozhu36** [spinnaker/community#15]
### Cloud Provider

Name of cloud provider AlibabaCloud(alicloud)

### Maintaining Organization(s)

- Alibaba Group

#### Point of Contact(s)

- @xiaozhu36

### Requirements

- [x] Cloud Provider will be actively backed by a development team from Maintainers with a significant stake in the project.
- [x] Maintainers commit to triaging and addressing major bugs and issues with the integration in a timely manner.
- [x] Maintainers commit to handling routine maintainence tasks for the integrations, such as:
  - [x] Keeping it compatible with updates to the cloud provider itself.
  - [x] Making any cloud provider-specific changes in response to global architecture changes within Spinnaker.
- [x] Maintainers acknowledge failure to maintain cloud provider integration may prompt removal of integration from Spinnaker.
- [x] Maintainers agree to setup and maintain a Special Interest Group for the Cloud Provider integration.

**Comment by robzienert** [comment]
TOC +1

**Comment by ezimanyi** [comment]
TOC +1

**Comment by ajordens** [comment]
TOC +1

**Comment by robzienert** [comment]
Approved. Thank you!
