### ISSUE TITLE
REQUEST: New Approver status for @fieldju

### ISSUE THREAD

**Issue by fieldju** [spinnaker/community#16]
### Github Username

@fieldju

### Requirements

- [x] Belongs to an organization with significant stake in project
- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Has reviewed 5 PRs of significant scope
- [x] Sponsored by 2 Approvers

### Sponsors

- @duftler 
- @maggieneterval
- @erikmunson 
- @cfieber 

##### Nike, Inc
We have integrated Kayenta into our Ci/Cd process and are committed to having it be part of our ACA solution.

##### Kayenta

1 open, 18 closed
https://github.com/spinnaker/kayenta/pulls?q=is%3Apr+author%3Afieldju+sort%3Acreated-asc

##### Deck Kayenta

1 closed
https://github.com/spinnaker/deck-kayenta/pulls?q=is%3Apr+author%3Afieldju+sort%3Acreated-asc

PRs and issues that I have reviewed and triaged
https://github.com/spinnaker/kayenta/issues?q=is%3Aissue+is%3Aclosed+assignee%3Afieldju
https://github.com/spinnaker/kayenta/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3Afieldju

**Comment by duftler** [comment]
+1

I am in favor of Justin becoming an Approver.

**Comment by maggieneterval** [comment]
+1

Would like to add that in addition to his development contributions, Justin is an active community member in Slack, often responding to community members who need help with canary-related issues. His team also participates in the UI SIG.

**Comment by erikmunson** [comment]
+1

I trust Justin to make good judgment calls around code contributions, technical direction, and relationships with other community members. He's highly engaged and effective in supporting community members on canary analysis and the Kayenta project in general, and I'd trust him to apply the same strengths to other areas of the Spinnaker project if he chose to get involved.

**Comment by robzienert** [comment]
TOC +1

**Comment by ajordens** [comment]
TOC +1 

Preference would be to create a new Github group for `kayenta-contributors` as the contributions thus far are Kayenta-specific (and we'd like to support this sort of contributor model for `kayenta`).

**Comment by ezimanyi** [comment]
TOC +1, and agree with @ajordens on the idea of scoping this to `kayenta`

**Comment by robzienert** [comment]
A new [oss-kayenta-approvers](https://github.com/orgs/spinnaker/teams/oss-kayenta-approvers) team has been created with write permissions to kayenta & deck-kayenta, with @fieldju as the seeding member. :)
