### ISSUE TITLE
PROPOSAL: New Cloud Provider for HuaweiCloud(huaweicloud)

### ISSUE THREAD

**Issue by niuzhenguo** [spinnaker/community#17]
### Cloud Provider

Name of cloud provider HuaweiCloud(huaweicloud)

### Maintaining Organization(s)

- Huawei

#### Point of Contact(s)

- @zengchen1024 @niuzhenguo

### Requirements

- [x] Cloud Provider will be actively backed by a development team from Maintainers with a significant stake in the project.
- [x] Maintainers commit to triaging and addressing major bugs and issues with the integration in a timely manner.
- [x] Maintainers commit to handling routine maintainence tasks for the integrations, such as:
  - [x] Keeping it compatible with updates to the cloud provider itself.
  - [x] Making any cloud provider-specific changes in response to global architecture changes within Spinnaker.
- [x] Maintainers acknowledge failure to maintain cloud provider integration may prompt removal of integration from Spinnaker.
- [x] Maintainers agree to setup and maintain a Special Interest Group for the Cloud Provider integration.

**Comment by robzienert** [comment]
HI, can you please offer more than 1 point of contact?

**Comment by niuzhenguo** [comment]
@robzienert sure! added @zengchen1024

**Comment by robzienert** [comment]
TOC +1

**Comment by ezimanyi** [comment]
TOC +1

**Comment by ajordens** [comment]
TOC +1

**Comment by robzienert** [comment]
@niuzhenguo TOC has approved this; sorry for the delay. Please see https://github.com/spinnaker/community/blob/master/cloud-provider-requirements.md for details on what all is involved.

**Comment by niuzhenguo** [comment]
@robzienert Thanks!
