### ISSUE TITLE
REQUEST: New Approver status for skandragon

### ISSUE THREAD

**Issue by skandragon** [spinnaker/community#24]
### Github Username

@skandragon

### Requirements

- [ X ] Belongs to an organization with significant stake in project
- [ X ] Known active participant in the community
- [ X ] Has submitted at least 5 PRs of significant scope that are merged
- [ X ] Is already fulfilling the Reviewer role
- [ X ] Has reviewed 5 PRs of significant scope
- [ X ] Sponsored by 2 Approvers

### Sponsors

- @duftler 
- @fieldju

### List of qualifications for this position

- Name of organization(s) with significant stake in project

OpsMX

- Links to public Spinnaker PRs

A lot of them on Kayenta, Orca, etc.  :)

**Comment by robzienert** [comment]
TOC +1

**Comment by fieldju** [comment]
+1

I am also in favor of Michael becoming an Approver.

**Comment by ezimanyi** [comment]
TOC +1

**Comment by aglover** [comment]
@ajordens what say you?

**Comment by ajordens** [comment]
TOC +1
