### ISSUE TITLE
REQUEST: New Approver status for clareliguori

### ISSUE THREAD

**Issue by clareliguori** [spinnaker/community#25]
### Github Username

@clareliguori

### Requirements

- [x] Belongs to an organization with significant stake in project
- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Is already fulfilling the Reviewer role
- [x] Has reviewed 5 PRs of significant scope
- [x] Sponsored by 2 Approvers

### Sponsors

- @emjburns
- @robzienert

### List of qualifications for this position

- Name of organization(s) with significant stake in project: AWS
- Links to public Spinnaker PRs:

Merged:
* https://github.com/spinnaker/clouddriver/pull/3604
* https://github.com/spinnaker/clouddriver/pull/3660
* https://github.com/spinnaker/clouddriver/pull/3238
* https://github.com/spinnaker/deck/pull/6687
* https://github.com/spinnaker/clouddriver/pull/2998

Reviewed:
* https://github.com/spinnaker/clouddriver/pull/3825
* https://github.com/spinnaker/clouddriver/pull/3633
* https://github.com/spinnaker/orca/pull/3016
* https://github.com/spinnaker/deck/pull/7162
* https://github.com/spinnaker/clouddriver/pull/3888

**Comment by ezimanyi** [comment]
TOC +1
