### ISSUE TITLE
REQUEST: New Reviewer status for german-muzquiz

### ISSUE THREAD

**Issue by german-muzquiz** [spinnaker/community#26]
### Github Username

@german-muzquiz

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @ethanfrogers
- @kevinawoo

### List of qualifications for this position

- https://github.com/spinnaker/gate/pull/675
- https://github.com/spinnaker/clouddriver/pull/3442
- https://github.com/spinnaker/halyard/pull/1252
- https://github.com/spinnaker/deck/pull/6937
- https://github.com/spinnaker/clouddriver/pull/3716
- https://github.com/spinnaker/clouddriver/pull/3961

**Comment by ethanfrogers** [comment]
+1

**Comment by robzienert** [comment]
TOC +1

**Comment by ajordens** [comment]
TOC +1
