### ISSUE TITLE
REQUEST: New Reviewer status for link108

### ISSUE THREAD

**Issue by link108** [spinnaker/community#28]
### Github Username

@link108

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- https://github.com/ethanfrogers
- https://github.com/robzienert

### List of qualifications for this position

- https://github.com/spinnaker/kork/pull/219
- https://github.com/spinnaker/kork/pull/217
- https://github.com/spinnaker/kork/pull/325
- https://github.com/spinnaker/kork/pull/358
- https://github.com/spinnaker/halyard/pull/1386
- https://github.com/spinnaker/orca/pull/3058
- https://github.com/spinnaker/deck/pull/6842

**Comment by kevinawoo** [comment]
Cameron puts out great stuff! I'm glad to put in my sponsorship for him to be a reviewer.

**Comment by robzienert** [comment]
TOC +1

**Comment by ajordens** [comment]
TOC +1

**Comment by ezimanyi** [comment]
TOC +1
