### ISSUE TITLE
REQUEST: New Approver status for plumpy

### ISSUE THREAD

**Issue by plumpy** [spinnaker/community#29]
### Github Username

@plumpy

### Requirements

- [:heavy_check_mark:] Belongs to an organization with significant stake in project
- [:heavy_check_mark:] Known active participant in the community
- [:heavy_check_mark:] Has submitted at least 5 PRs of significant scope that are merged
- [:heavy_check_mark:] Is already fulfilling the Reviewer role
- [:heavy_check_mark:] Has reviewed 5 PRs of significant scope
- [:heavy_check_mark:] Sponsored by 2 Approvers

### Sponsors

@ezimanyi 
@maggieneterval 

### List of qualifications for this position

- Name of organization(s) with significant stake in project
![Super Old Google Logo](https://1c7qp243xy9g1qeffp1k1nvo-wpengine.netdna-ssl.com/wp-content/uploads/2018/03/1_Google-logo-1998.jpg)

- Links to public Spinnaker PRs
https://github.com/spinnaker/clouddriver/pull/3968
https://github.com/spinnaker/clouddriver/pull/3932
https://github.com/spinnaker/fiat/pull/443
https://github.com/spinnaker/clouddriver/pull/3970

**Comment by maggieneterval** [comment]
:+1: :heavy_check_mark: :man_technologist: :heart:

**Comment by ezimanyi** [comment]
+1 as sponsor for this proposal
+1 as my TOC vote

**Comment by duftler** [comment]
I support adding Plumpy as an Approver.

**Comment by robzienert** [comment]
+1 TOC.

💯 jpeg quality Google logo.
