### ISSUE TITLE
REQUEST: New TOC member for plumpy

### ISSUE THREAD

**Issue by plumpy** [spinnaker/community#32]
### Github Username
@plumpy

### Requirements

- [:+1:] I am a Spinnaker Approver already
- [:+1:] I have enabled 2FA on my Github account
- [:+1:] I have one sponsor within the Steering Committee
- [:+1:] I have spoken to my sponsor(s) ahead of this application, and they have agreed to sponsor my application

### Sponsors

@duftler 
@ezimanyi 

### List of qualifications for this position

- Prior open source experience
  - https://secure2.linuxjournal.com/ljarchive/LJ/107/6489.html
  - http://lkml.iu.edu/hypermail/linux/kernel/0308.1/1798.html
  - https://willysr.blogspot.com/2004/11/another-updates-for-gaim.html
  - https://fossies.org/linux/xmms/ChangeLog
  - https://plugins.jetbrains.com/plugin/8527-google-java-format
- Links to public contributions showing your technical command of the Spinnaker project
  - See #29

**Comment by ezimanyi** [comment]
I would definitely support having @plumpy join the TOC.

**Comment by duftler** [comment]
I support @plumpy joining the TOC.

**Comment by aglover** [comment]
SC voted. +1 from all.
