### ISSUE TITLE
SIG proposal:  operational validation

### ISSUE THREAD

**Issue by skandragon** [spinnaker/community#37]
I propose that we create a SIG that is focused on techniques and developing working code to improve operational validation, which will include canary analysis as well as others such as progressive deployment driven by observed behavior.  This is a widely defined scope, and if needed we can split it into smaller sections, but we did not want to limit it to just a specific strategy.

Proposed leads:  Michael Graff, Chris Sanden, Matt Duftler

Proposed meeting cadence:  Either monthly or every 2 weeks.  We may start more frequent but change as we evolve.

**Comment by ajordens** [comment]
Can we make this a PR along the lines of https://github.com/spinnaker/community/pull/20

**Comment by skandragon** [comment]
Sure.  I wasn't sure what the preferred method is, as it's pretty much undocumented.  I assumed that, if accepted as a SIG, I'd be suggesting such a PR.  Does doing the work to make the pages updated mean this has been accepted?
