### ISSUE TITLE
REQUEST: New Reviewer status for brian-armory

### ISSUE THREAD

**Issue by brian-armory** [spinnaker/community#38]
### Github Username

@brian-armory 

### Requirements

- [ ] Known active participant in the community
- [ ] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @ethanfrogers
- @kevinawoo

### List of qualifications for this position

- [Documentation SIG](https://github.com/spinnaker/community/pull/20)

**Comment by ethanfrogers** [comment]
+1

**Comment by kevinawoo** [comment]
👍 	from me! I can't wait to see all the new docs docs docs

**Comment by ezimanyi** [comment]
TOC +1 for reviewer status to docs repository

**Comment by ethanfrogers** [comment]
@ezimanyi @robzienert is there any update on this?

**Comment by ezimanyi** [comment]
Needs a vote from @robzienert @plumpy @ajordens

**Comment by plumpy** [comment]
Sorry for the delay on this. I discussed this with the TOC and we decided to add a `docs-approvers` team with merge access to the `spinnaker.github.io` repo

This is done now and you should have received an invite to that team. Let me know if you have any issues or there are other things you need access to and we can figure out how to widen the scope...
