### ISSUE TITLE
REQUEST: New Reviewer status for jonsie

### ISSUE THREAD

**Issue by jonsie** [spinnaker/community#45]
### Github Username

@jonsie

### Requirements

- [X] Known active participant in the community
- [X] Has submitted at least 5 PRs of significant scope that are merged
- [X] Sponsored by 2 Approvers

### Sponsors

- @robzienert 
- @marchello2000 

### List of qualifications for this position

- https://github.com/spinnaker/orca/pull/3228 (open)
- https://github.com/spinnaker/orca/commits?author=jonsie
- https://github.com/spinnaker/clouddriver/commits?author=jonsie
- https://github.com/spinnaker/fiat/commits?author=jonsie
- https://github.com/spinnaker/front50/commits?author=jonsie
- https://github.com/spinnaker/rosco/commits?author=jonsie
- https://github.com/spinnaker/roer/commits?author=jonsie

**Comment by robzienert** [comment]
I'm sponsoring.

**Comment by marchello2000** [comment]
me too

**Comment by ezimanyi** [comment]
TOC +1

**Comment by jonsie** [comment]
This should wrap it up: https://github.com/spinnaker/community/pull/46

**Comment by robzienert** [comment]
TOC +1
