### ISSUE TITLE
REQUEST: New Reviewer status for gal-yardeni

### ISSUE THREAD

**Issue by gal-yardeni** [spinnaker/community#47]
### Github Username : gal-yardeni

e.g. (at)github_user

### Requirements

- [ ] Known active participant in the community
- [ ] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- (at)sponsor-1 : Emily Burns (@emjburns )
- (at)sponsor-2 : Mark Vulfson (@marchello2000 )

### List of qualifications for this position
- part of the Spinnaker team @ Netflix.

**Comment by plumpy** [comment]
Hi Gal! One of the requirements for reviewer is to have sent "5 PRs of significant scope that are merged". So far I just see one merged PR, so perhaps this could be reopened later?

Sorry for the bad/annoying news!

**Comment by robzienert** [comment]
Closing for now, until all 3 qualifications are in place.
