### ISSUE TITLE
REQUEST: New Reviewer status for aravindmd

### ISSUE THREAD

**Issue by aravindmd** [spinnaker/community#48]
### Github Username

@aravindmd 

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @marchello2000 
- @jeyrschabu 

### List of qualifications for this position

- https://github.com/spinnaker/clouddriver/commits?author=aravindmd
- https://github.com/spinnaker/orca/commits?author=aravindmd
- https://github.com/spinnaker/swabbie/commits?author=aravindmd

**Comment by robzienert** [comment]
TOC +1

**Comment by ezimanyi** [comment]
TOC +1

**Comment by plumpy** [comment]
TOC +1

**Comment by ajordens** [comment]
TOC +1

**Comment by ajordens** [comment]
l
