### ISSUE TITLE
REQUEST: New Reviewer status for pdelagrave

### ISSUE THREAD

**Issue by pdelagrave** [spinnaker/community#54]
### Github Username

@pdelagrave

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @ezimanyi
- @Jammy-Louie

### List of qualifications for this position

* [Halyard Boot2 migration](https://github.com/spinnaker/halyard/pull/1328)
* ["Run Job" stage support for CloudFoundry](https://github.com/spinnaker/clouddriver/pull/3789)
* [New Halyard option to select an image variant when deploying Spinnaker on k8s](https://github.com/spinnaker/halyard/pull/1401)
* Ubuntu image variant support:
  * [Build system](https://github.com/spinnaker/spinnaker/pull/4774)
  * Every service: [clouddriver](https://github.com/spinnaker/clouddriver/pull/3964), [echo](https://github.com/spinnaker/echo/pull/628) [front50](https://github.com/spinnaker/front50/pull/575), [orca](https://github.com/spinnaker/orca/pull/3113), +6 other...
* 35 total code PRs merged in spinnaker
* [7 docs PRs merged](https://github.com/spinnaker/spinnaker.github.io/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Apdelagrave+)

**Comment by ezimanyi** [comment]
I'll happily sponsor @pdelagrave becoming a reviewer based on the work cited above.

Also +1 as my official TOC vote.

**Comment by Jammy-Louie** [comment]
@pdelagrave has helped do a lot of great work to support and help spinnaker grow and I am happy to sponsor.

**Comment by plumpy** [comment]
TOC +1

**Comment by robzienert** [comment]
TOC +1

**Comment by ajordens** [comment]
TOC +1

**Comment by ethanfrogers** [comment]
TOC +1(00)!
