### ISSUE TITLE
REQUEST: New Approver status for caseyhebebrand

### ISSUE THREAD

**Issue by caseyhebebrand** [spinnaker/community#56]
### Github Username

caseyhebebrand

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors
@christopherthielen 
@alanmquach

### List of qualifications for this position

- Organizations with a stake in Spinnaker: Netflix

Author:

- [Show icon for target group registration in progress](https://github.com/spinnaker/deck/pull/7502)
- [Type field for CLB details](https://github.com/spinnaker/deck/pull/7504)
- [Disable CLB deletion if instances exist](https://github.com/spinnaker/deck/pull/7509)
- [Target Group health check URL](https://github.com/spinnaker/deck/pull/7520)
- [Refer to Jenkins controller](https://github.com/spinnaker/deck/pull/7531)
- [Show load balancer warning based on settings](feat(provider/aws): Show load balancer warning based on settings)
- 2 package bumps

Reviewer:
- [Functions listing and searching](https://github.com/spinnaker/deck/pull/7536)
- [Reactify delete application section](https://github.com/spinnaker/deck/pull/7501)
- [Allow markdown in validation message](https://github.com/spinnaker/deck/pull/7510)
- [Reactify edit application modal](https://github.com/spinnaker/deck/pull/7545)
- [Preventing edits against orphaned load balancers](https://github.com/spinnaker/deck/pull/7529)

**Comment by ezimanyi** [comment]
TOC +1

**Comment by ethanfrogers** [comment]
TOC +1

**Comment by plumpy** [comment]
TOC +1
