### ISSUE TITLE
REQUEST: New Approver status for aravindmd

### ISSUE THREAD

**Issue by aravindmd** [spinnaker/community#59]
### Github Username

 @aravindmd

### Requirements

- [x] Belongs to an organization with significant stake in project
- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Is already fulfilling the Reviewer role
- [x] Has reviewed 5 PRs of significant scope
- [x] Sponsored by 2 Approvers

### Sponsors

- @jeyrschabu
- @marchello2000

### List of qualifications for this position

- Member of Spinnaker team @ Netflix
- PR's authored
     * https://github.com/spinnaker/clouddriver/commits?author=aravindmd
     * https://github.com/spinnaker/orca/commits?author=aravindmd
     * https://github.com/spinnaker/swabbie/commits?author=aravindmd
- PR's reviewed
     * https://github.com/spinnaker/swabbie/pull/292
     * https://github.com/spinnaker/swabbie/pull/293
     * https://github.com/spinnaker/swabbie/pull/233
     * https://github.com/spinnaker/orca/pull/3011
     * https://github.com/spinnaker/gate/pull/764
     * https://github.com/spinnaker/orca/pull/2935

**Comment by ajordens** [comment]
TOC +1

**Comment by ezimanyi** [comment]
TOC +1

**Comment by ethanfrogers** [comment]
TOC +1

**Comment by plumpy** [comment]
TOC +1
