### ISSUE TITLE
REQUEST: New TOC member for ezimanyi

### ISSUE THREAD

**Issue by ezimanyi** [spinnaker/community#6]
### Github Username
@ezimanyi

### Requirements

- [x] I am a Spinnaker Approver already
- [x] I have enabled 2FA on my Github account
- [x] I have one sponsor within the Steering Committee
- [x] I have spoken to my sponsor(s) ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @duftler 
- @skim1420 

### List of qualifications for this position

- Strong contributor to the OSS Spinnaker project over the past ~1.5 years.
   - Top 5 contributor to most of the core Spinnaker repos (by commits) in that timeframe
   - Made a number of wide-reaching refactors, particularly to orca, igor, and clouddriver-kubernetes
   - Active in triaging/resolving issues, particularly in the kubernetes provider

**Comment by duftler** [comment]
+1

I am in favor of adding @ezimanyi as a TOC member.

**Comment by skim1420** [comment]
+1

**Comment by robzienert** [comment]
TOC +1

**Comment by ajordens** [comment]
TOC +1

**Comment by aglover** [comment]
I am in favor! +1.

**Comment by pstout** [comment]
Based on the context provided by Eric and the TOC input, I in favor of Eric joining the TOC.
+1

**Comment by rmeshenberg** [comment]
+1.  I support Eric joining TOC.

**Comment by duftler** [comment]
After unanimous vote, adding Eric Zimanyi to the two relevant locations:

https://github.com/spinnaker/community/pull/8
https://github.com/spinnaker/spinnaker.github.io/pull/1405

**Comment by aglover** [comment]
Congrats @ezimanyi and welcome to the Spinnaker TOC!
