### ISSUE TITLE
REQUEST: New Approver status for jonsie

### ISSUE THREAD

**Issue by jonsie** [spinnaker/community#60]
### Github Username

@jonsie 

### Requirements

- [X] Belongs to an organization with significant stake in project
- [X] Known active participant in the community
- [X] Has submitted at least 5 PRs of significant scope that are merged
- [X] Is already fulfilling the Reviewer role
- [X] Has reviewed 5 PRs of significant scope
- [x] Sponsored by 2 Approvers

### Sponsors

- @robzienert 
- @marchello2000

### List of qualifications for this position

- Name of organization(s) with significant stake in project

Netflix

- Links to public Spinnaker PRs

Open:
 
https://github.com/spinnaker/clouddriver/pull/4155
https://github.com/spinnaker/front50/pull/625 (and https://github.com/spinnaker/front50/pull/621)

Commits:

https://github.com/spinnaker/orca/commits?author=jonsie
https://github.com/spinnaker/clouddriver/commits?author=jonsie
https://github.com/spinnaker/kork/commits?author=jonsie
https://github.com/spinnaker/front50/commits?author=jonsie
https://github.com/spinnaker/fiat/commits?author=jonsie
https://github.com/spinnaker/rosco/commits?author=jonsie

**Comment by ajordens** [comment]
TOC +1

**Comment by ezimanyi** [comment]
TOC +1

**Comment by ethanfrogers** [comment]
TOC +1

**Comment by plumpy** [comment]
TOC +1
