### ISSUE TITLE
REQUEST: New Reviewer status for gal-yardeni

### ISSUE THREAD

**Issue by gal-yardeni** [spinnaker/community#61]
### Github Username

gal-yardeni

### Requirements

- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Sponsored by 2 Approvers

### Sponsors

- @emjburns 
- @marchello2000 

### List of qualifications for this position

Organizations with a stake in Spinnaker: Netflix

- Links to public Spinnaker PRs:

Author:
1. [orca/precondition: Add a custom message to precondition](https://github.com/spinnaker/deck/pull/7448)
2. [orca/monitor-deploy: Completed event should include details of success/failure](https://github.com/spinnaker/orca/pull/3214)
3. [deck/baseOS : Adding display name property for the bakery baseOs options](https://github.com/spinnaker/deck/pull/7464)
4. [gate/baseOS: Add displayName to baseOS](https://github.com/spinnaker/gate/pull/914)
5. [keel/deleteApp: Delete all data for an application](https://github.com/spinnaker/keel/pull/587)

Reviewer:
1. [feat(monitoreddeploy): allow overriding maxAnalysisMinutes and failOnError](https://github.com/spinnaker/orca/pull/3261) 
2. [docs(managed): add overview and reference for resource statuses](https://github.com/spinnaker/spinnaker.github.io/pull/1585)
3. [feat(rollback): avoid scaling down during rollback](https://github.com/spinnaker/orca/pull/3185)
4. [feat(managed): add resource status to infrastructure views](https://github.com/spinnaker/deck/pull/7590)
5. [fix(actuation): correctly detect active actuations for multi-region resources](https://github.com/spinnaker/keel/pull/597)
6. [fix(webhook): Don't try to deserialize fields we don't really need](https://github.com/spinnaker/orca/pull/3202)

**Comment by ethanfrogers** [comment]
TOC +1!

**Comment by robzienert** [comment]
TOC +1

**Comment by gal-yardeni** [comment]
Closing this issue as I've opened a request for approval role: https://github.com/spinnaker/community/issues/63
