### ISSUE TITLE
REQUEST: New Approver status for gal-yardeni

### ISSUE THREAD

**Issue by gal-yardeni** [spinnaker/community#63]
### Github Username

gal-yardeni

### Requirements

- [x] Belongs to an organization with significant stake in project
- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Is already fulfilling the Reviewer role
- [x] Has reviewed 5 PRs of significant scope
- [x] Sponsored by 2 Approvers

### Sponsors

- @emjburns 
- @marchello2000 

### List of qualifications for this position

- Name of organization(s) with significant stake in project: Netflix
- Links to public Spinnaker PRs:

Created by me:
[orca/precondition: Add a custom message to precondition](https://github.com/spinnaker/deck/pull/7448)
[orca/monitor-deploy: Completed event should include details of success/failure](https://github.com/spinnaker/orca/pull/3214)
[deck/baseOS : Adding display name property for the bakery baseOs options](https://github.com/spinnaker/deck/pull/7464)
[gate/baseOS: Add displayName to baseOS](https://github.com/spinnaker/gate/pull/914)
[keel/deleteApp: Delete all data for an application](https://github.com/spinnaker/keel/pull/587)

Reviewed by me:
[feat(monitoreddeploy): allow overriding maxAnalysisMinutes and failOnError](https://github.com/spinnaker/orca/pull/3261)
[docs(managed): add overview and reference for resource statuses](https://github.com/spinnaker/spinnaker.github.io/pull/1585)
[feat(rollback): avoid scaling down during rollback](https://github.com/spinnaker/orca/pull/3185)
[feat(managed): add resource status to infrastructure views](https://github.com/spinnaker/orca/pull/3185)
[fix(actuation): correctly detect active actuations for multi-region resources](https://github.com/spinnaker/keel/pull/597)
[fix(webhook): Don't try to deserialize fields we don't really need](https://github.com/spinnaker/orca/pull/3202)
+ Some more...

**Comment by ethanfrogers** [comment]
TOC +1

**Comment by robzienert** [comment]
TOC +1

**Comment by ajordens** [comment]
TOC +1

**Comment by luispollo** [comment]
Added https://github.com/spinnaker/community/pull/69 to make this easier.
