### ISSUE TITLE
REQUEST: New Approver status for luispollo

### ISSUE THREAD

**Issue by luispollo** [spinnaker/community#64]
### Github Username

@luispollo

### Requirements

- [x] Belongs to an organization with significant stake in project
- [x] Known active participant in the community
- [x] Has submitted at least 5 PRs of significant scope that are merged
- [x] Is already fulfilling the Reviewer role
- [x] Has reviewed 5 PRs of significant scope
- [x] Sponsored by 2 Approvers

### Sponsors

- @emjburns 
- @robfletcher 
- @erikmunson 

### List of qualifications for this position

- Name of organization(s) with significant stake in project: Netflix
- Links to public Spinnaker PRs
  - Created by me:
    - [feat(resource-status): Return PAUSED status for vetoed resources](https://github.com/spinnaker/keel/pull/572)
    - [feat(serialization): Use friendly names for artifact types](https://github.com/spinnaker/keel/pull/560)
    - [fix(rrb): Store RRB before-cleanup pipeline ID in the right context field](https://github.com/spinnaker/orca/pull/3239)
    - [fix(bake): Fix the fix for inconsistent names in parallel bakes](https://github.com/spinnaker/orca/pull/3236)
    - [fix(notifications): Don't send failure notifications for cancelled pipelines and stages](https://github.com/spinnaker/echo/pull/663)
    - etc.
  - Reviewed by me:
    - [don't treat missing AMI as a fatal resolution error](https://github.com/spinnaker/keel/pull/591)
    - [feat(deleteApp): Delete all data for an application](https://github.com/spinnaker/keel/pull/587)
    - [feat(environments): allowed-times constraint](https://github.com/spinnaker/keel/pull/586)
    - [feat(core/managed): visually refresh/rebrand infra details indicator](https://github.com/spinnaker/deck/pull/7617)
    - [feat(core/managed): add deep links to status reference doc](https://github.com/spinnaker/deck/pull/7610)
    - etc.

**Comment by ethanfrogers** [comment]
TOC +1

**Comment by ajordens** [comment]
TOC +1

**Comment by robzienert** [comment]
TOC +1

**Comment by luispollo** [comment]
Added https://github.com/spinnaker/community/pull/69 to make this easier.
