### ISSUE TITLE
REQUEST: New Reviewer status for <srekapalli>

### ISSUE THREAD

**Issue by srekapalli** [spinnaker/community#72]
### Github Username

@srekapalli

### Sponsors

- @cfieber 
- @marchello2000 

### List of qualifications for this position

**Merged PR's**

[spinnaker/gate feat(cors): Configurable whitelist of origins ](https://github.com/spinnaker/gate/pull/891)

[spinnaker/orca fix(SpEL): Execution context injected into expressions dynamically](https://github.com/spinnaker/orca/pull/3142)

[spinnaker/orca fix(webhooks): Construct Webhook status check URL honoring the](https://github.com/spinnaker/orca/pull/3187)

[spinnaker/front50 feat(PostgreSQL DB Storage): Added support for Postgres.](https://github.com/spinnaker/front50/pull/635)

[spinnaker/orca feat(executions): Adding new ADMIN endpoint to import execution ](https://github.com/spinnaker/orca/pull/3310)

[spinnaker/kork feat(sql): Support for multiple SQL data sources ](https://github.com/spinnaker/kork/pull/424)

[spinnaker/front50 feat(sql): Enables composite storage service to be backed by SQL](https://github.com/spinnaker/front50/pull/641)

**Comment by cfieber** [comment]
big 👍 from me - @srekapalli has done some great stuff so far!

**Comment by ethanfrogers** [comment]
TOC +1

**Comment by ezimanyi** [comment]
TOC +1

**Comment by plumpy** [comment]
TOC +1

**Comment by ajordens** [comment]
TOC +1
