### ISSUE TITLE
REQUEST: New Approver status for @srekapalli

### ISSUE THREAD

**Issue by srekapalli** [spinnaker/community#77]
### Github Username

e.g. @srekapalli

### Sponsors

- @cfieber 
- @marchello2000 

### List of qualifications for this position

**Organization**
- Netflix.

**Links to public Spinnaker PRs**

[spinnaker/gate feat(cors): Configurable whitelist of origins ](https://github.com/spinnaker/gate/pull/891)

[spinnaker/orca fix(SpEL): Execution context injected into expressions dynamically](https://github.com/spinnaker/orca/pull/3142)

[spinnaker/orca fix(webhooks): Construct Webhook status check URL honoring the](https://github.com/spinnaker/orca/pull/3187)

[spinnaker/front50 feat(PostgreSQL DB Storage): Added support for Postgres.](https://github.com/spinnaker/front50/pull/635)

[spinnaker/orca feat(executions): Adding new ADMIN endpoint to import execution ](https://github.com/spinnaker/orca/pull/3310)

[spinnaker/kork feat(sql): Support for multiple SQL data sources ](https://github.com/spinnaker/kork/pull/424)

[spinnaker/front50 feat(sql): Enables composite storage service to be backed by SQL](https://github.com/spinnaker/front50/pull/641)

**PRs Reviewed.**
[feat(expressions): Enhance expression evaluation order](https://github.com/spinnaker/orca/pull/3286)

[feat(plugins): Remote plugin download capabilities](https://github.com/spinnaker/kork/pull/434)

[feat(slack): Add slack service](https://github.com/spinnaker/gate/pull/955) 

[feat(aggregator): enables customization of permission aggregation as well as permission sources](https://github.com/spinnaker/fiat/pull/481)

[refactor(titus): Allow serde of operation descriptions ](https://github.com/spinnaker/clouddriver/pull/4001)

[spinnaker/keel Limit number of events in history ](https://github.com/spinnaker/keel/pull/410)

**Comment by ajordens** [comment]
TOC +1

**Comment by ethanfrogers** [comment]
TOC +1

**Comment by ezimanyi** [comment]
TOC +1

**Comment by plumpy** [comment]
TOC +1
