### ISSUE TITLE
PROPOSAL: New Cloud Provider for TencentCloud(tencent)

### ISSUE THREAD

**Issue by shengyu** [spinnaker/community#79]
### Cloud Provider

Name of cloud provider TencentCloud(tencent)

### Maintaining Organization(s)

- Tencent

#### Point of Contact(s)

- @shengyu @donghun221

### Requirements

- [x] Cloud Provider will be actively backed by a development team from Maintainers with a significant stake in the project.
- [x] Maintainers commit to triaging and addressing major bugs and issues with the integration in a timely manner.
- [x] Maintainers commit to handling routine maintainence tasks for the integrations, such as:
  - [x] Keeping it compatible with updates to the cloud provider itself.
  - [x] Making any cloud provider-specific changes in response to global architecture changes within Spinnaker.
- [x] Maintainers acknowledge failure to maintain cloud provider integration may prompt removal of integration from Spinnaker.
- [x] Maintainers agree to setup and maintain a Special Interest Group for the Cloud Provider integration.

**Comment by ezimanyi** [comment]
TOC +1

**Comment by plumpy** [comment]
TOC +1

**Comment by robzienert** [comment]
TOC +1

**Comment by robzienert** [comment]
Approved by majority of TOC.

**Comment by robzienert** [comment]
@shengyu @donghun221 Please create a Tencent Cloud SIG proposal as well, as this is necessary for continued cloud provider support.

**Comment by shengyu** [comment]
@robzienert  I will submit a SIG proposal. Thanks for the approval.
