### ISSUE TITLE
REQUEST: New Reviewer status for plumpy

### ISSUE THREAD

**Issue by plumpy** [spinnaker/community#9]
### Github Username

@plumpy

### Requirements

- [X] Known active participant in the community
- [X] Has submitted at least 5 PRs of significant scope that are merged
- [X] Sponsored by 2 Approvers

### Sponsors

@ezimanyi
@duftler 

### List of qualifications for this position

https://github.com/spinnaker/gate/pull/775
https://github.com/spinnaker/clouddriver/pull/3578
https://github.com/spinnaker/orca/pull/2872
https://github.com/spinnaker/clouddriver/pull/3715
https://github.com/spinnaker/clouddriver/pull/3815

**Comment by ezimanyi** [comment]
+1
I support granting @plumpy reviewer status

**Comment by duftler** [comment]
+1
I support this as well.

**Comment by plumpy** [comment]
cc @robzienert @ajordens

**Comment by robzienert** [comment]
+1

**Comment by ajordens** [comment]
+1

**Comment by ajordens** [comment]
Added to https://github.com/spinnaker/spinnaker/blob/master/reviewers.md and sent invite to join the `Reviewers` GitHub team.
